### ISSUE TITLE
Testing if fedora is used

### ISSUE THREAD

**Issue by obonaventure** [Aperence/linfo1341-congestion-student#1]
The current start script uses systemctl to stop firewalls if running on fedora. It should look at the contents of /etc/os-release to check if fedora is running and should restart the firewall after that. I would suggest to warn the user that the firewall is stopped

**Comment by Aperence** [comment]
Hello,

I've added these checks in the start and clean script, thank you for the proposition of looking at `etc/os-release`. 

It now ask first the user if it is allowed to shutdown his firewall, and proceed only if the user reply with 'Y'.

The cleaning script also ask the user if he wants his firewall to be restarted automatically, thus avoiding some operations for the user (even though it is only a one line command), and ensuring that he hasn't forgotten that his firewall is down.
